version: '3.8'

services:
  myapp:
    container_name: myapp
    build: .
    ports:
      - "3000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/admin
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    command: --bind_ip_all
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:

